port: ":8001"
# Room live time in seconds (0 for no timeout)
timeout: 10
# Show debug messages
debug: true
# Allowed origin for connections (* for any)
# e.g. "http://localhost:8080"
allowed_origin: "*"